<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />

	<title>Ops! Ha ocurrido un error en la página</title>

	<!-- Google fonts -->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />

	<!-- JQuery -->
	<script type="text/javascript" src="<?= $this->basePath(); ?>/public/libs/jquery-2.1.1/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="<?= $this->basePath(); ?>/public/libs/carhartl-jquery-cookie-92b7715/jquery.cookie.js"></script>

	<!-- Semantic UI -->
	<link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/libs/semantic-ui-0.18.0/packaged/css/semantic.min.css" media="all" />
	<script type="text/javascript" src="<?= $this->basePath(); ?>/public/libs/semantic-ui-0.18.0/packaged/javascript/semantic.min.js"></script>

	<!-- Login -->
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/login/css/demo.css" />
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/login/css/style.css" />
	<link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/login/css/animate-custom.css" />

    <!-- Calendario -->
    <script type="text/javascript" src="<?= $this->basePath(); ?>/public/libs/calendario-1.9/js/jscal2.js"></script>
    <script type="text/javascript" src="<?= $this->basePath(); ?>/public/libs/calendario-1.9/js/lang/en.js"></script>
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/libs/calendario-1.9/css/jscal2.css" />
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/libs/calendario-1.9/css/border-radius.css" />
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/libs/calendario-1.9/css/steel/steel.css" />    

	<!-- App -->
	<link rel="stylesheet" href="<?= $this->basePath(); ?>/public/css/app.css" media="all" />
    <script type="text/javascript" src="<?= $this->basePath(); ?>/public/js/core.js"></script>
    <script type="text/javascript" src="<?= $this->basePath(); ?>/public/js/app.js"></script>
    <script type="text/javascript" src="<?= $this->basePath(); ?>/public/js/persistent.js"></script>
</head>

<body data-path='<?= $this->basePath(); ?>'>
    <div class="container">
        <!-- Codrops top bar -->
        <div class="codrops-top">
            <a href="<?= $this->basePath() ?>">
                <strong>&laquo; MEDICADIZ S.A.S. </strong>
            </a>

            <span class="right">
                <a href="<?= $this->basePath() . "/public/Info/About/index" ?>">
                    <strong>Acerca</strong>
                </a>
            </span>
            <div class="clr"></div>
        </div><!--/ Codrops top bar -->

        <header>
            <h1 id="app-title">OPS! <span>HA OCURRIDO UN ERROR</span></h1>
        </header>

        <section>	
            <div id="container_demo" >

                <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  -->
                <a class="hiddenanchor" id="toregister"></a>
                <a class="hiddenanchor" id="tologin"></a>

				<div id="wrapper"><?= $this->content(); ?></div>
    
            </div>  
        </section>
    </div>	
</body>

</html>