<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <title>Pleets Apps</title>

    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="<?= $this->basePath(); ?>/public/libs/materialize/css/materialize.min.css"  media="screen,projection"/>

	<!-- Google fonts -->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type='text/css' />
    
    <script type="text/javascript" src="<?= $this->basePath(); ?>/public/js/html5shiv.js"></script>
    <script type="text/javascript" src="<?= $this->basePath(); ?>/public/js/respond.min.js"></script>

	<!-- jQuery -->
    <script type="text/javascript" src="<?= $this->basePath(); ?>/public/libs/jquery/jquery-2.1.1/jquery-2.1.1.min.js"></script>

    <!--Import materialize.js-->
    <script type="text/javascript" src="<?= $this->basePath(); ?>/public/libs/materialize/js/materialize.min.js"></script>

    <!-- CodeMirror -->
    <link rel="stylesheet" href="<?= $this->basePath(); ?>/public/libs/CodeMirror/lib/codemirror.css" type='text/css' />
    <link rel="stylesheet" href="<?= $this->basePath(); ?>/public/libs/CodeMirror/theme/monokai.css" type='text/css' />
    <script src="<?= $this->basePath(); ?>/public/libs/CodeMirror/lib/codemirror.js"></script>
    <script src="<?= $this->basePath(); ?>/public/libs/CodeMirror/mode/php/php.js"></script>
    <script src="<?= $this->basePath(); ?>/public/libs/CodeMirror/mode/clike/clike.js"></script>
    <script src="<?= $this->basePath(); ?>/public/libs/CodeMirror/mode/htmlmixed/htmlmixed.js"></script>
    <script src="<?= $this->basePath(); ?>/public/libs/CodeMirror/mode/xml/xml.js"></script>
    <script src="<?= $this->basePath(); ?>/public/libs/CodeMirror/mode/javascript/javascript.js"></script>
    <script src="<?= $this->basePath(); ?>/public/libs/CodeMirror/mode/css/css.js"></script>
    <script src="<?= $this->basePath(); ?>/public/libs/CodeMirror/addon/selection/active-line.js"></script>    
    <script src="<?= $this->basePath(); ?>/public/libs/CodeMirror/addon/edit/matchbrackets.js"></script>    

	<!-- App -->
	<link rel="stylesheet" href="<?= $this->basePath(); ?>/public/css/pleets.css" media="all" />
    <script type="text/javascript" src="<?= $this->basePath(); ?>/public/js/pleets.js"></script>
</head>

<body data-path='<?= $this->basePath(); ?>'>

    <nav>
        <div class="nav-wrapper">
            <a href="<?= $this->basePath() . '/public/Pleets' ?>" class="brand-logo"><i class="material-icons circle">folder</i></a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="https://github.com/Pleets/Drone" target="_blank">GitHub</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <?= $this->content(); ?>        
    </div>

</body>

</html>