<?php
	if ($this->isParam('file')):
		$file = $this->param('file');
		?>
		<h5><?= $file ?></h5>

		<div class="progress" id='save-file-action-loader' style='display: none'>
			<div class="indeterminate"></div>
		</div>

		<div id="save-file-action-response" style='display: none'></div>

		<form id="save-file-action" action="<?= $this->basePath().'/public/Pleets/Files/saveFile' ?>" method="post">
			<input type="hidden" name='file' value="<?= $file ?>" />
			<textarea id="file-edition" name="file-edition"><?= file_get_contents($file) ?></textarea>
			<button class="waves-effect waves-light btn" type="submit">Guardar</button>
			<?php if ($this->param('type') == 'controller'): ?>
				<a class="waves-effect waves-light btn" id='get-views-from-controller' data-module='<?= $this->param('module') ?>' data-controller='<?= strstr(basename($this->param('file')), '.', true) ?>' href="<?= $this->basePath() .'/public/Pleets/App/getViewsFromControler' ?>">Vistas</a>
			<?php elseif ($this->param('type') == 'view'): ?>
				<a class="waves-effect waves-light btn" target="_blank" href="<?= $this->basePath() .'/public/'. $this->param('module') .'/'. $this->param('controller') .'/'. strstr(basename($this->param('file')), '.', true)?>">Vista</a>
			<?php endif; ?>
		</form>
		<script>
		var editor = CodeMirror.fromTextArea(document.getElementById("file-edition"), {
	        lineNumbers: true,
	        matchBrackets: true,
	        mode: "application/x-httpd-php",
	        indentUnit: 4,
	        indentWithTabs: true,
	        theme: 'monokai',
		});
		</script>
		<?php
	else:
		?><div class="card-panel red">File not found!</div><?php
	endif;
?>

<?php if ($this->param('type') == 'controller'): ?>
<!-- Modal Structure -->
<div id="show-views-from-controller" class="modal">
	<div class="modal-content">
		<div class="progress">
			<div class="indeterminate"></div>
		</div>
	</div>
	<div class="modal-footer">
		<a href="#!" class="modal-action modal-close waves-effect btn-flat">Cancel</a>
	</div>
</div>
<?php endif; ?>