<?php $this->setTitle("Drone Index") ?>

<div class="jumbotron">
 	<h1>Application</h1>
 	<p>Copyright <?= date("Y") ?></p>
 	<p><a class="btn btn-primary btn-lg" href="<?= $this->basePath() ?>/public/App/Index/start" role="button"><span class="glyphicon glyphicon-th-large"></span> Start</a></p>
</div>

<div class="page-header">
  <h1>Example page header <small>Subtext for header</small></h1>
</div>

<div class="row">
  	<div class="col-sm-3 col-md-3 col-xs-6">
    	<div class="thumbnail">
      		<img src="<?= $this->basePath() ?>/public/img/thumb.svg" alt="image" style="height: 100px; display: block;">
      		<div class="caption">
	        	<h3>Thumbnail label</h3>
	        	<p>...</p>
	        	<p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      		</div>
	    </div>
  	</div>
  	<div class="col-sm-3 col-md-3 col-xs-6">
    	<div class="thumbnail">
      		<img src="<?= $this->basePath() ?>/public/img/thumb.svg" alt="image" style="height: 100px; display: block;">
      		<div class="caption">
	        	<h3>Thumbnail label</h3>
	        	<p>...</p>
	        	<p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      		</div>
	    </div>
  	</div>
  	<div class="col-sm-3 col-md-3 col-xs-6">
    	<div class="thumbnail">
      		<img src="<?= $this->basePath() ?>/public/img/thumb.svg" alt="image" style="height: 100px; display: block;">
      		<div class="caption">
	        	<h3>Thumbnail label</h3>
	        	<p>...</p>
	        	<p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      		</div>
	    </div>
  	</div>
  	<div class="col-sm-3 col-md-3 col-xs-6">
    	<div class="thumbnail">
      		<img src="<?= $this->basePath() ?>/public/img/thumb.svg" alt="image" style="height: 100px; display: block;">
      		<div class="caption">
	        	<h3>Thumbnail label</h3>
	        	<p>...</p>
	        	<p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      		</div>
	    </div>
  	</div>
</div>

<br /><br />