<?php if ($this->param("process") == "success"): ?>

	<?php $data = $this->param("data"); ?>

	<?php if (count($data)): ?>
		<table class="table table-striped table-hovered">
			<thead>

				<?php
					$columns = array_keys($data[0]);

					$string_columns = array();

					foreach ($columns as $col):
						if (is_string($col))
							$string_columns[] = $col;
					endforeach;
				?>
				<tr>
					<?php for ($i = 0; $i < count($string_columns); $i++): ?>
						<th><?= $string_columns[$i] ?></th>
					<?php endfor; ?>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($data as $row): ?>
					<tr>
						<td><?= $row[0] ?></td>
						<td><?= $row[1] ?></td>
						<td><?= $row[2] ?></td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	<?php else: ?>
		?><div class="alert alert-warning">There are not data to show!</div>
	<?php endif; ?>

<?php elseif ($this->param("process") == "error"): ?>

	<div class="alert alert-danger"><?= $this->param("message") ?></div>

<?php else: ?>

	<div class="alert alert-danger">Unknown error!</div>

<?php endif; ?>