<div class="row">
	<div class="col s12 m6">
		<div class="card blue-grey darken-1">
			<div class="card-content white-text">
				<span class="card-title">Project</span>
				<p>To view the state of your project!</p>
			</div>
			<div class="card-action">
				<a href="<?= $this->basePath() ?>/public/?module=Pleets&controller=App&view=modules">Modules</a>
				<a href="<?= $this->basePath() ?>/public/?module=Pleets&controller=App&view=appFullVersion&folder=module">Module version</a>
				<a href="<?= $this->basePath() ?>/public/?module=Pleets&controller=App&view=appFullVersion&folder=Framework">Core version</a>
			</div>
		</div>
	</div>
</div>
