<?php $this->setTitle("Drone Index") ?>

<div class="jumbotron">
    <h1>DronePHP <small>Framework</small></h1>
    <p>Make it easy!</p>
    <p>
        <a target="_blank" class="btn btn-primary btn-lg" href="http://www.dronephp.com" role="button">
            <span class="glyphicon glyphicon-share"></span> Go to Website
        </a>
    </p>
</div>

<p class="justify">
    This is a simple skeleton application for your project!.
</p>

<br /><br />