<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />

	<title>API</title>

	<!-- Google fonts -->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />

	<!-- Le Styles -->
	<link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/libs/bootstrap-3.1.1/css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/libs/jquery-ui-1.10.4/themes/flick/jquery-ui.css" />
	<link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/libs/CSS-Render/css-render.css" />
	<link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/libs/JScript-Render/css/JScriptRender.css" />

	<!-- Scripts -->
	<script type="text/javascript" src="<?= $this->basePath(); ?>/public/js/html5shiv.js"></script>
	<script type="text/javascript" src="<?= $this->basePath(); ?>/public/js/respond.min.js"></script>
	<script type="text/javascript" src="<?= $this->basePath(); ?>/public/libs/jquery/jquery-2.1.1/jquery-2.1.1.min.js"></script>
	<script type="text/javascript" src="<?= $this->basePath(); ?>/public/libs/jquery/plugins/carhartl-jquery-cookie-92b7715/jquery.cookie.js"></script>
	<script type="text/javascript" src="<?= $this->basePath(); ?>/public/libs/jquery-ui-1.10.4/ui/jquery-ui.js"></script>
	<script type="text/javascript" src="<?= $this->basePath(); ?>/public/libs/bootstrap-3.1.1/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="<?= $this->basePath(); ?>/public/libs/JScript-Render/JScriptRender.js"></script>
	<script type="text/javascript" src="<?= $this->basePath(); ?>/public/js/persistent.js"></script>
	<script type="text/javascript" src="<?= $this->basePath(); ?>/public/js/settings.js"></script>
	<script type="text/javascript" src="<?= $this->basePath(); ?>/public/js/live.js"></script>


	<!-- App -->
	<link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/css/app.css" media="all" />
	<link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/css/pleets.css" media="all" />

    <script type="text/javascript" src="<?= $this->basePath(); ?>/public/js/app.js"></script>
    <script type="text/javascript" src="<?= $this->basePath(); ?>/public/js/pleets.js"></script>
</head>

<body data-path='<?= $this->basePath(); ?>'>

	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="<?= $this->basePath(); ?>/public/Api">General API</a>
	    </div>
	  </div><!-- /.container-fluid -->
	</nav>

	<div class="container">
		<?= $this->content(); ?>
	</div>

</body>

</html>