<?php $this->setTitle("Form Validator") ?>

<div class="page-header">
 	<h1>Form Validations <small>backend</small></h1>
</div>

<form action="<?= $this->basePath() ?>/public/App/Form/validator" method="post">
	<div class="row">
		<div class="col-sm-6">
			<div class="form-grup">
				<label for="fname">First Name</label>
				<input type="text" class="form-control" id="fname" name="fname" placeholder="first name" />
			</div>
		</div>
		<div class="col-sm-6">
			<div class="form-group">
				<label for="lname">Last Name</label>
				<input type="text" class="form-control" id="lname" name="lname" placeholder="last name" />
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-4">
			<div class="form-group">
				<label for="address">Address</label>
				<input type="text" class="form-control" id="address" name="address" placeholder="address" />
			</div>
		</div>
		<div class="col-sm-3">
			<div class="form-group">
				<label for="height">Height (m)</label>
				<input type="text" class="form-control" id="height" name="height" placeholder="x.x" />
			</div>
		</div>
		<div class="col-sm-5">
			<div class="form-group">
				<label for="email">Email address</label>
				<input type="email" class="form-control" id="email" name="email" placeholder="email" />
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6">
			<div class="form-group">
				<label for="password">Password</label>
				<input type="password" class="form-control" id="password" name="password" placeholder="Password" />
			</div>
		</div>
		<div class="col-sm-6">
			<div class="form-group">
				<label for="birthday">Birthday</label>
				<input type="text" class="form-control" id="date" name="date" placeholder="yyyy-mm-dd" />
			</div>
		</div>
		<div class="col-sm-6">
			<div class="form-group">
				<label for="url">Website</label>
				<input type="text" class="form-control" id="url" name="url" placeholder="http://www.example.com" />
			</div>
		</div>
	</div>
	<button type="submit" class="btn btn-default">Submit</button>
</form><br />

<?php if ($this->isParam("success")): ?>

	<?php if ($this->param("success")): ?>

		<div class="alert alert-success">
			<strong>Success!</strong> The form is valid!
		</div>

	<?php elseif ($this->isParam("messages")): ?>

		<?php foreach ($this->param("messages") as $input => $messages): ?>

			<article>
				<strong><?= $input ?></strong><br />
				<ul>
					<?php foreach ($messages as $code => $message): ?>
						<li><?= $message ?></li>
					<?php endforeach; ?>
				</ul>
			</article>

		<?php endforeach; ?>

	<?php else: ?>

		<div class="alert alert-warning">
			<strong>Warning!</strong> <?= $this->param("message") ?>
		</div>

	<?php endif; ?>

<?php endif; ?>
